version: "3.9"
services:
    mongo:
        build:
            context: './'
            dockerfile: mongo.Dockerfile
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
            - MONGO_INITDB_DATABASE=jury
            - MONGO_REPLICA_SET_NAME=rs0
        ports:
            - 127.0.0.1:27107:27017
        volumes:
            - './data:/data/db'
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
        networks:
            - jury-network

    mongorssetup:
        depends_on:
            - 'mongo'
        image: mongo:latest
        environment:
            - MONGODB_USER=${MONGODB_USER}
            - MONGODB_PASS=${MONGODB_PASS}
        volumes:
            - .:/scripts
        restart: "no"
        entrypoint: [ 'bash', '/scripts/init-mongo-rs.sh' ]
        networks:
            - jury-dev-network

    rust:
        depends_on:
            - 'mongo'
            - 'mongorssetup'
        container_name: jury-main
        environment:
            - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - REACT_APP_JURY_NAME=${JURY_NAME}
            - PORT=8000
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                - REACT_APP_JURY_NAME=${JURY_NAME}
                - REACT_APP_JURY_URL=/api
                - REACT_APP_HUB=${HEHE:-}
        ports:
            - ${PORT:-8000}:8000
        networks:
            - jury-network

networks:
    jury-network:
        driver: bridge