# FROM mongo:6.0.4
FROM mongo:latest

RUN openssl rand -base64 756 > /keyfile
RUN chmod 400 /keyfile
RUN chown 999:999 /keyfile

ENV MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
ENV MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
ENV MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
ENV MONGO_REPLICA_SET_NAME=$MONGO_REPLICA_SET_NAME

CMD ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/keyfile"]
