name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jury:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jury:${{ github.sha }}
          build-args: |
            VITE_JURY_NAME=${{ secrets.JURY_NAME }}
            VITE_HUB=${{ secrets.HUB_URL }}
            VITE_JURY_URL=${{ secrets.JURY_URL }}
      
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            # Exit on any error
            set -e
            
            echo "Starting deployment..."

            echo "Cloning or updating repo..."

            if [ -d ~/jury ]; then
                cd ~/jury
                git pull origin main
            else
                git clone https://github.com/hackutd/jury.git ~/jury
                cd ~/jury
            fi

            echo "Repo updated"
            
            echo "Stopping existing containers..."
            docker-compose down || {
              echo "Warning: Failed to stop existing containers"
            }
            
            echo "Starting new containers..."
            docker-compose up -d || {
              echo "Failed to start containers"
              exit 1
            }
            
            echo "Deployment successful!"
