name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  backend-test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Test Script
        run: |
          ./scripts/test-runner.sh
