name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  backend-test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Test Script
        run: |
          echo "JURY_ADMIN_PASSWORD=admin\nEMAIL_FROM=test@example.com\nEMAIL_HOST=smtp.example.com\nEMAIL_USERNAME=test\nEMAIL_PASSWORD=test" >> .env
          ./scripts/test-runner.sh
